- name: installScript JG
  hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: Copy SSH Keys
      include_tasks: ./tasks/copy_ssh_keys.yml
      tags:
        - ssh

    - name: Install Docker
      include_tasks: ./tasks/install_docker.yml
      tags:
        - docker

