- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - docker

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  tags:
    - docker

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  tags:
    - docker

- name: Update the apt package index (again)
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - docker

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: present
  tags:
    - docker

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
  tags:
    - docker

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
